/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SyncswapRouter } from "./SyncswapRouter";
export * as factories from "./factories";
export { SyncswapRouter__factory } from "./factories/SyncswapRouter__factory";
