/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VelocoreVault } from "./VelocoreVault";
export * as factories from "./factories";
export { VelocoreVault__factory } from "./factories/VelocoreVault__factory";
