import fs from "fs";

const transformImport = (source: string) =>
  `import { ${source}Interface } from "../types/ethers-v6/${source}/${source}";`;

const transformType = (source: string) => `${source}: ${source}Interface;`;

const fillGetEthersInterface = (params: {
  sources: string[];
  outputFile: string;
}) => {
  const { sources, outputFile } = params;

  const importsData = sources.map(transformImport).join("\n");

  const typesData = sources.map(transformType).join("\n");

  const data = `/* Autogenerated file. Do not edit manually. */
import fs from "fs";
import path from "path";
import { ethers } from "ethers";

${importsData}

type ContractRec = {
${typesData}
};

const getEthersInterface = <C extends keyof ContractRec>(name: C) => {
  const abiPath = path.join("./src/abi/sources/", name + ".json");

  const abiStr = fs.readFileSync(abiPath, { encoding: "utf-8" });

  const contract = new ethers.Interface(
    abiStr
  ) as unknown as ContractRec[typeof name];

  return contract;
};

export default getEthersInterface;

`;

  fs.writeFileSync(outputFile, data, { encoding: "utf-8" });
};

export default fillGetEthersInterface;
