export const ACTION_PROVIDER_SYNCSWAP = "SYNCSWAP";
export const ACTION_PROVIDER_PANCAKE = "PANCAKE";
export const ACTION_PROVIDER_VELOCORE = "VELOCORE";
export const ACTION_PROVIDER_DMAIL = "DMAIL";
export const ACTION_PROVIDER_OPEN_OCEAN = "OPEN_OCEAN";
export const ACTION_PROVIDER_XY_FINANCE = "XY_FINANCE";
export const ACTION_PROVIDER_WOOFI = "WOOFI";
export const ACTION_PROVIDER_LINEA_BANK = "LINEA_BANK";

const ACTION_PROVIDERS = [
  ACTION_PROVIDER_SYNCSWAP,
  ACTION_PROVIDER_PANCAKE,
  ACTION_PROVIDER_VELOCORE,
  ACTION_PROVIDER_DMAIL,
  ACTION_PROVIDER_OPEN_OCEAN,
  ACTION_PROVIDER_XY_FINANCE,
  ACTION_PROVIDER_WOOFI,
  ACTION_PROVIDER_LINEA_BANK,
] as const;
export default ACTION_PROVIDERS;
