export const ACTION_SYNC_SWAP_ROUTER = "SYNC_SWAP_ROUTER";
export const ACTION_PANCAKE_ROUTER = "PANCAKE_ROUTER";
export const ACTION_VELOCORE_VAULT = "VELOCORE_VAULT";
export const ACTION_DMAIL = "DMAIL";
export const ACTION_OPEN_OCEAN_ROUTER = "OPEN_OCEAN_ROUTER";
export const ACTION_XY_FINANCE_ROUTER = "XY_FINANCE_ROUTER";
export const ACTION_WOOFI_ROUTER = "WOOFI_ROUTER";

export const ACTIONS = [
  ACTION_SYNC_SWAP_ROUTER,
  ACTION_PANCAKE_ROUTER,
  ACTION_VELOCORE_VAULT,
  ACTION_DMAIL,
  ACTION_OPEN_OCEAN_ROUTER,
  ACTION_XY_FINANCE_ROUTER,
  ACTION_WOOFI_ROUTER,
] as const;
