export const BLOCK_TEST_BLOCK = "TEST_BLOCK";
export const BLOCK_SYNC_SWAP_ETH_USDC_SWAP = "SYNC_SWAP_ETH_USDC_SWAP";
export const BLOCK_SYNC_SWAP_ETH_WBTC_SWAP = "SYNC_SWAP_ETH_WBTC_SWAP";
export const BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP = "SYNC_SWAP_ETH_CEBUSD_SWAP";
export const BLOCK_VELOCORE_ETH_USDC_SWAP = "VELOCORE_ETH_USDC_SWAP";
export const BLOCK_VELOCORE_ETH_CEBUSD_SWAP = "VELOCORE_ETH_CEBUSD_SWAP";
export const BLOCK_DMAIL_SEND_MAIL = "DMAIL_SEND_MAIL";
export const BLOCK_OPEN_OCEAN_ETH_USDC_SWAP = "OPEN_OCEAN_ETH_USDC_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_IUSD_SWAP = "OPEN_OCEAN_ETH_IUSD_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_IZI_SWAP = "OPEN_OCEAN_ETH_IZI_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_WAVAX_SWAP = "OPEN_OCEAN_ETH_WAVAX_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_WMATIC_SWAP = "OPEN_OCEAN_ETH_WMATIC_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_WBNB_SWAP = "OPEN_OCEAN_ETH_WBNB_SWAP";
export const BLOCK_OPEN_OCEAN_ETH_CEBUSD_SWAP = "OPEN_OCEAN_ETH_CEBUSD_SWAP";
export const BLOCK_XY_FINANCE_ETH_CEBUSD_SWAP = "XY_FINANCE_ETH_CEBUSD_SWAP";
export const BLOCK_XY_FINANCE_ETH_USDC_SWAP = "XY_FINANCE_ETH_USDC_SWAP";
export const BLOCK_XY_FINANCE_ETH_USDT_SWAP = "XY_FINANCE_ETH_USDT_SWAP";
export const BLOCK_PANCAKE_ETH_USDC_SWAP = "PANCAKE_ETH_USDC_SWAP";

export const BLOCKS = [
  BLOCK_TEST_BLOCK,
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_PANCAKE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_DMAIL_SEND_MAIL,
  BLOCK_OPEN_OCEAN_ETH_USDC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IUSD_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IZI_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WAVAX_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WMATIC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WBNB_SWAP,
  BLOCK_OPEN_OCEAN_ETH_CEBUSD_SWAP,
  BLOCK_XY_FINANCE_ETH_CEBUSD_SWAP,
  BLOCK_XY_FINANCE_ETH_USDC_SWAP,
  BLOCK_XY_FINANCE_ETH_USDT_SWAP,
  BLOCK_PANCAKE_ETH_USDC_SWAP,
] as const;
