export const CONTRACT_DMAIL = "Dmail";
export const CONTRACT_ECHO_DEX_ROUTER = "EchoDexRouter";
export const CONTRACT_ERC_20 = "Erc20";
export const CONTRACT_LINEA_BANK_CORE = "LineaBankCore";
export const CONTRACT_LINEA_BANK_LAB_DISTRIBUTOR = "LineaBankLabDistributor";
export const CONTRACT_OPEN_OCEAN_EXCHANGE = "OpenOceanExchange";
export const CONTRACT_PANCAKE_FACTORY = "PancakeFactory";
export const CONTRACT_PANCAKE_QUOTE = "PancakeQuote";
export const CONTRACT_PANCAKE_SWAP_ROUTER = "PancakeSwapRouter";
export const CONTRACT_SYNCSWAP_CLASSIC_POOL_FACTORY =
  "SyncswapClassicPoolFactory";
export const CONTRACT_SYNCSWAP_ROUTER = "SyncswapRouter";
export const CONTRACT_VELOCORE_FACTORY = "VelocoreFactory";
export const CONTRACT_VELOCORE_VAULT = "VelocoreVault";
export const CONTRACT_WOOFI_ROUTER = "WoofiRouter";
export const CONTRACT_XY_FINANCE_ROUTER = "XyFinanceRouter";

export const CONTRACTS = [
  CONTRACT_DMAIL,
  CONTRACT_ECHO_DEX_ROUTER,
  CONTRACT_ERC_20,
  CONTRACT_LINEA_BANK_CORE,
  CONTRACT_LINEA_BANK_LAB_DISTRIBUTOR,
  CONTRACT_PANCAKE_FACTORY,
  CONTRACT_PANCAKE_QUOTE,
  CONTRACT_PANCAKE_SWAP_ROUTER,
  CONTRACT_SYNCSWAP_CLASSIC_POOL_FACTORY,
  CONTRACT_SYNCSWAP_ROUTER,
  CONTRACT_VELOCORE_FACTORY,
  CONTRACT_VELOCORE_VAULT,
  CONTRACT_WOOFI_ROUTER,
  CONTRACT_XY_FINANCE_ROUTER,
] as const;
