export const CONTRACT_XY_FINANCE_ROUTER = "XY_FINANCE_ROUTER";
export const CONTRACT_OPEN_OCEAN_EXCHANGE = "OPEN_OCEAN_EXCHANGE";

const CONTRACTS_WITHOUT_ABI = [
  CONTRACT_XY_FINANCE_ROUTER,
  CONTRACT_OPEN_OCEAN_EXCHANGE,
] as const;

export default CONTRACTS_WITHOUT_ABI;
