/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VelocoreFactory } from "./VelocoreFactory";
export * as factories from "./factories";
export { VelocoreFactory__factory } from "./factories/VelocoreFactory__factory";
