import fs from "fs";

import { constantCase } from "change-case";

const transformExport = (source: string) =>
  `export const CONTRACT_${constantCase(source)} = "${source}";`;

const transformDefaultExport = (source: string) =>
  `\tCONTRACT_${constantCase(source)},`;

const fillConstants = (params: { sources: string[]; outputFile: string }) => {
  const { sources, outputFile } = params;

  const exportsData = sources.map(transformExport).join("\n");

  const defaultExportData = sources.map(transformDefaultExport).join("\n");

  const data = `/* Autogenerated file. Do not edit manually. */
${exportsData}

const CONTRACTS = [
${defaultExportData}
] as const;

export default CONTRACTS;
`;

  fs.writeFileSync(outputFile, data, { encoding: "utf-8" });
};

export default fillConstants;
