import {
  BLOCK_DMAIL_SEND_MAIL,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
} from "../../common/constants";

const availableBlocks = [
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_DMAIL_SEND_MAIL,
] as const;

export default availableBlocks;
