import {
  BLOCK_DMAIL_SEND_MAIL,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_USDC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IUSD_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IZI_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WAVAX_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WMATIC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WBNB_SWAP,
  BLOCK_OPEN_OCEAN_ETH_CEBUSD_SWAP,
} from "../../common/constants";

const availableBlocks = [
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_DMAIL_SEND_MAIL,
  BLOCK_OPEN_OCEAN_ETH_USDC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IUSD_SWAP,
  BLOCK_OPEN_OCEAN_ETH_IZI_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WAVAX_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WMATIC_SWAP,
  BLOCK_OPEN_OCEAN_ETH_WBNB_SWAP,
  BLOCK_OPEN_OCEAN_ETH_CEBUSD_SWAP,
] as const;

export default availableBlocks;
