/* Autogenerated file. Do not edit manually. */
import fs from "fs";
import path from "path";

import { ethers } from "ethers";

import {
  CONTRACT_DMAIL,
  CONTRACT_ECHO_DEX_SMART_ROUTER,
  CONTRACT_ERC20,
  CONTRACT_LINEA_BANK_CORE,
  CONTRACT_LINEA_BANK_LAB_DISTRIBUTOR,
  CONTRACT_PANCAKE_FACTORY,
  CONTRACT_PANCAKE_QUOTE,
  CONTRACT_PANCAKE_SWAP_ROUTER,
  CONTRACT_SYNCSWAP_CLASSIC_POOL_FACTORY,
  CONTRACT_SYNCSWAP_ROUTER,
  CONTRACT_VELOCORE_FACTORY,
  CONTRACT_VELOCORE_VAULT,
  CONTRACT_WOOFI_ROUTER,
} from "../constants/contracts";
import { DmailInterface } from "../types/ethers-v6/Dmail/Dmail";
import { EchoDexSmartRouterInterface } from "../types/ethers-v6/EchoDexSmartRouter/EchoDexSmartRouter";
import { Erc20Interface } from "../types/ethers-v6/Erc20/Erc20";
import { LineaBankCoreInterface } from "../types/ethers-v6/LineaBankCore/LineaBankCore";
import { LineaBankLabDistributorInterface } from "../types/ethers-v6/LineaBankLabDistributor/LineaBankLabDistributor";
import { PancakeFactoryInterface } from "../types/ethers-v6/PancakeFactory/PancakeFactory";
import { PancakeQuoteInterface } from "../types/ethers-v6/PancakeQuote/PancakeQuote";
import { PancakeSwapRouterInterface } from "../types/ethers-v6/PancakeSwapRouter/PancakeSwapRouter";
import { SyncswapClassicPoolFactoryInterface } from "../types/ethers-v6/SyncswapClassicPoolFactory/SyncswapClassicPoolFactory";
import { SyncswapRouterInterface } from "../types/ethers-v6/SyncswapRouter/SyncswapRouter";
import { VelocoreFactoryInterface } from "../types/ethers-v6/VelocoreFactory/VelocoreFactory";
import { VelocoreVaultInterface } from "../types/ethers-v6/VelocoreVault/VelocoreVault";
import { WoofiRouterInterface } from "../types/ethers-v6/WoofiRouter/WoofiRouter";

export type ContractRec = {
  [CONTRACT_DMAIL]: DmailInterface;
  [CONTRACT_ECHO_DEX_SMART_ROUTER]: EchoDexSmartRouterInterface;
  [CONTRACT_ERC20]: Erc20Interface;
  [CONTRACT_LINEA_BANK_CORE]: LineaBankCoreInterface;
  [CONTRACT_LINEA_BANK_LAB_DISTRIBUTOR]: LineaBankLabDistributorInterface;
  [CONTRACT_PANCAKE_FACTORY]: PancakeFactoryInterface;
  [CONTRACT_PANCAKE_QUOTE]: PancakeQuoteInterface;
  [CONTRACT_PANCAKE_SWAP_ROUTER]: PancakeSwapRouterInterface;
  [CONTRACT_SYNCSWAP_CLASSIC_POOL_FACTORY]: SyncswapClassicPoolFactoryInterface;
  [CONTRACT_SYNCSWAP_ROUTER]: SyncswapRouterInterface;
  [CONTRACT_VELOCORE_FACTORY]: VelocoreFactoryInterface;
  [CONTRACT_VELOCORE_VAULT]: VelocoreVaultInterface;
  [CONTRACT_WOOFI_ROUTER]: WoofiRouterInterface;
};

const getEthersInterface = <C extends keyof ContractRec>(args: { name: C }) => {
  const { name } = args;

  const abiPath = path.join("./src/abi/sources/", name + ".json");

  const abiStr = fs.readFileSync(abiPath, { encoding: "utf-8" });

  const contract = new ethers.Interface(
    abiStr,
  ) as unknown as ContractRec[typeof name];

  return contract;
};

export default getEthersInterface;
