export const ACTION_SYNC_SWAP_ROUTER = "SYNC_SWAP_ROUTER";
export const ACTION_PANCAKE_ROUTER = "PANCAKE_ROUTER";
export const ACTION_VELOCORE_VAULT = "VELOCORE_VAULT";
export const ACTION_DMAIL = "DMAIL";

export const ACTIONS = [
  ACTION_SYNC_SWAP_ROUTER,
  ACTION_PANCAKE_ROUTER,
  ACTION_VELOCORE_VAULT,
  ACTION_DMAIL,
] as const;
