export const BLOCK_TEST_BLOCK = "TEST_BLOCK";
export const BLOCK_SYNC_SWAP_ETH_USDC_SWAP = "SYNC_SWAP_ETH_USDC_SWAP";
export const BLOCK_SYNC_SWAP_ETH_WBTC_SWAP = "SYNC_SWAP_ETH_WBTC_SWAP";
export const BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP = "SYNC_SWAP_ETH_CEBUSD_SWAP";
export const BLOCK_PANCAKE_ETH_USDC_SWAP = "PANCAKE_ETH_USDC_SWAP";
export const BLOCK_VELOCORE_ETH_USDC_SWAP = "VELOCORE_ETH_USDC_SWAP";
export const BLOCK_VELOCORE_ETH_CEBUSD_SWAP = "VELOCORE_ETH_CEBUSD_SWAP";
export const BLOCK_DMAIL_SEND_MAIL = "DMAIL_SEND_MAIL";

export const BLOCKS = [
  BLOCK_TEST_BLOCK,
  BLOCK_SYNC_SWAP_ETH_USDC_SWAP,
  BLOCK_SYNC_SWAP_ETH_WBTC_SWAP,
  BLOCK_SYNC_SWAP_ETH_CEBUSD_SWAP,
  BLOCK_PANCAKE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_USDC_SWAP,
  BLOCK_VELOCORE_ETH_CEBUSD_SWAP,
  BLOCK_DMAIL_SEND_MAIL,
] as const;
