export const CONTRACT_ERC_20 = "ERC_20";

export const CONTRACT_SYNC_SWAP_ROUTER = "SYNC_SWAP_ROUTER";
export const CONTRACT_SYNC_SWAP_CLASSIC_POOL_FACTORY =
  "SYNC_SWAP_CLASSIC_POOL_FACTORY";

export const CONTRACT_PANCAKE_SWAP_ROUTER = "PANCAKE_SWAP_ROUTER";
export const CONTRACT_PANCAKE_FACTORY = "PANCAKE_FACTORY";
export const CONTRACT_PANCAKE_QUOTE = "PANCAKE_QUOTE";

export const CONTRACT_VELOCORE_VAULT = "VELOCORE_VAULT";
export const CONTRACT_VELOCORE_FACTORY = "VELOCORE_FACTORY";

export const CONTRACT_DMAIL = "DMAIL";

export const CONTRACT_OPEN_OCEAN_EXCHANGE = "OPEN_OCEAN_EXCHANGE";

export const CONTRACT_XY_FINANCE_ROUTER = "XY_FINANCE_ROUTER";

export const CONTRACTS = [
  CONTRACT_ERC_20,
  CONTRACT_SYNC_SWAP_ROUTER,
  CONTRACT_SYNC_SWAP_CLASSIC_POOL_FACTORY,
  CONTRACT_PANCAKE_SWAP_ROUTER,
  CONTRACT_PANCAKE_FACTORY,
  CONTRACT_PANCAKE_QUOTE,
  CONTRACT_VELOCORE_VAULT,
  CONTRACT_VELOCORE_FACTORY,
  CONTRACT_DMAIL,
  CONTRACT_XY_FINANCE_ROUTER,
] as const;
