/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PancakeQuote extends BaseContract {
  public constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PancakeQuote;
  clone(): PancakeQuote;
  methods: {
    quoteExactInputSingle(
      params: [
        string,
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ]
    ): NonPayableTransactionObject<{
      amountOut: string;
      sqrtPriceX96After: string;
      initializedTicksCrossed: string;
      gasEstimate: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
