/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dmail } from "./Dmail";
export * as factories from "./factories";
export { Dmail__factory } from "./factories/Dmail__factory";
