/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Dmail, DmailInterface } from "../Dmail";

const _abi = [
  {
    name: null,
    type: "constructor",
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    gas: null,
    _isFragment: true,
  },
  {
    type: "function",
    name: "send_mail",
    constant: false,
    inputs: [
      {
        name: "to",
        type: "string",
        baseType: "string",
        _isParamType: true,
      },
      {
        name: "subject",
        type: "string",
        baseType: "string",
        _isParamType: true,
      },
    ],
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    gas: null,
    _isFragment: true,
  },
] as const;

export class Dmail__factory {
  static readonly abi = _abi;
  static createInterface(): DmailInterface {
    return new Interface(_abi) as DmailInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Dmail {
    return new Contract(address, _abi, runner) as unknown as Dmail;
  }
}
