/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SyncswapClassicPoolFactory } from "./SyncswapClassicPoolFactory";
export * as factories from "./factories";
export { SyncswapClassicPoolFactory__factory } from "./factories/SyncswapClassicPoolFactory__factory";
