/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LineaBankLabDistributor } from "./LineaBankLabDistributor";
export * as factories from "./factories";
export { LineaBankLabDistributor__factory } from "./factories/LineaBankLabDistributor__factory";
